fprintf(fileID,'source_surf = .false. \n');
% source_point_x=transducer_length/transducer_number*iact_each;
xs_str = sprintf('xs = %6.5f \n', tempx);
fprintf(fileID,xs_str);
zs_str = sprintf('zs = %6.5f \n', tempy);
fprintf(fileID,zs_str);
fprintf(fileID,'source_type = %d \n', src.source_type);
fprintf(fileID,'time_function_type = %d \n',src.time_function_type);
name_of_source_file_str = sprintf('name_of_source_file          = %s%04d \n',strrep(src.name_of_source_folder,'\','//'), s_num-1); 
%name_of_source_file_str = sprintf('name_of_source_file          =  %04d \n',s_num-1);
fprintf(fileID,name_of_source_file_str);
fprintf(fileID,'burst_band_width = 200.415 \n');
fprintf(fileID,'f0 = %6.3f \n',src.f0);
fprintf(fileID,'tshift = 0 \n');
fprintf(fileID,'anglesource = 0.00 \n');
fprintf(fileID,'Mxx = 1.000000 \n');
fprintf(fileID,'Mzz = 1.000000 \n');
fprintf(fileID,'Mxz = 0.000000 \n');
fprintf(fileID,'factor = 1000.000 \n');